<?php

// Read only
return [
    [
        "/",
        "home",
        "Main",
        "index",
        "GET"
    ],
    [
        "/about",
        "about",
        "Main",
        "about",
        "GET"
    ],
    [
        "/contact",
        "contact",
        "Main",
        "contact",
        "GET"
    ],
    [
        "/tos",
        "terms of service",
        "Main",
        "tos",
        "GET"
    ],
    [
        "/login",
        "login",
        "Main",
        "login",
        "GET"
    ],
    [
        "/posts/{page:i}",
        "list",
        "Posts",
        "listPost",
        "GET"
    ],
    [
        "/post/{post:a}",
        "show",
        "Posts",
        "showPost",
        "GET"
    ],
    [
        "/favorite/{from:*}",
        "favorite",
        "Posts",
        "favorite",
        "POST" 
    ],
    [
        "/add_comment/{post:a}",
        "add",
        "Comments",
        "add",
        "POST"
    ],
    [
        "/report/{post:a}",
        "report",
        "Comments",
        "report",
        "POST"
    ],

    // ADMIN

    [
        "/admin/login",
        "",
        "Admin",
        "login",
        "POST"
    ],
    [
        "/admin/dashboard",
        "dashboard",
        "Admin",
        "dashboard",
        "GET"
    ],
    [
        "/admin/edition/{page:i}",
        "edition",
        "Posts",
        "edition",
        "GET"
    ],
    [
        "/admin/moderation",
        "moderation",
        "Posts",
        "moderation",
        "GET"
    ],
];